name = "agtor"
uuid = "95dc4c25-59f6-4b9e-a920-4913b22a8444"
authors = ["ConnectedSystems"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
